"""empty message

Revision ID: 6b2c688787c9
Revises: 91a6ee7a4486
Create Date: 2022-01-04 22:54:02.069545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b2c688787c9'
down_revision = '91a6ee7a4486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('productos',
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('os_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['os.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'os_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('os')
    # ### end Alembic commands ###
